import { lotStore } from '../data/mockLots';
import type { BuyerRequirement, LotMatch, MarketplaceTransaction, Offer, ProduceLot } from '../types/marketplace';

const KEY = 'krishimitra_marketplace';
type Database = { requirements: BuyerRequirement[]; offers: Offer[]; transactions: MarketplaceTransaction[] };
const read = (): Database => { try { const saved = localStorage.getItem(KEY); return saved ? JSON.parse(saved) : { requirements: [], offers: [], transactions: [] }; } catch { return { requirements: [], offers: [], transactions: [] }; } };
const write = (db: Database) => { localStorage.setItem(KEY, JSON.stringify(db)); window.dispatchEvent(new Event('krishimitra_marketplace_updated')); };
const lots = (): ProduceLot[] => lotStore.getAll().filter((lot) => lot.qualityGrade).map((lot, index) => ({ id: index === 0 ? 'LOT-001' : lot.id.toUpperCase(), farmerId: 'FARMER-001', crop: lot.crop, quantity: Number(lot.quantity.replace(/,/g, '')), unit: 'KG', qualityGrade: lot.qualityGrade!, district: lot.district?.replace(' District', '') || 'Nashik', state: lot.state || 'Maharashtra', availabilityStatus: lot.status === 'COMPLETED' ? 'UNAVAILABLE' : 'READY', sourceType: 'FARMER' }));
const match = (requirement: BuyerRequirement, lot: ProduceLot, index: number): LotMatch => { const cropCompatible = lot.crop.toLowerCase() === requirement.crop.toLowerCase(); const qualityCompatible = requirement.acceptedQualityGrades.includes(lot.qualityGrade); const locationCompatible = lot.district.toLowerCase() === requirement.district.toLowerCase(); const availabilityCompatible = lot.availabilityStatus === 'READY'; const quantityCompatibility = lot.quantity >= requirement.quantityRequired ? 'FULL' : lot.quantity >= requirement.minimumAcceptableLotQuantity ? 'PARTIAL' : 'NONE'; const eligible = cropCompatible && qualityCompatible && locationCompatible && availabilityCompatible && quantityCompatibility !== 'NONE'; return { id: `${requirement.id}-${lot.id}`, requirementId: requirement.id, lotId: lot.id, cropCompatible, qualityCompatible, locationCompatible, availabilityCompatible, quantityCompatibility, distanceKm: 12 + index * 8, overallStatus: eligible ? quantityCompatibility === 'FULL' ? 'MATCHED' : 'PARTIAL_MATCH' : 'NOT_ELIGIBLE', reasons: [cropCompatible ? 'Crop match' : 'Different crop', qualityCompatible ? 'Quality match' : 'Quality not accepted', locationCompatible ? 'Location match' : 'Outside preferred location', quantityCompatibility === 'PARTIAL' ? 'Partial quantity match' : quantityCompatibility === 'FULL' ? 'Full quantity match' : 'Lot quantity below minimum'] }; };
export const marketplaceService = {
  getRequirements: async () => read().requirements,
  createRequirement: async (requirement: BuyerRequirement) => { const db = read(); db.requirements.unshift(requirement); write(db); return requirement; },
  updateRequirement: async (id: string, changes: Partial<BuyerRequirement>) => { const db = read(); const item = db.requirements.find((r) => r.id === id); if (!item) throw new Error('Requirement not found'); Object.assign(item, changes); write(db); return item; },
  getLots: async () => lots(), getLot: async (id: string) => lots().find((lot) => lot.id === id) || null,
  getMatches: async (requirementId: string) => { const requirement = read().requirements.find((r) => r.id === requirementId); return requirement ? lots().map((lot, index) => ({ lot, match: match(requirement, lot, index) })).filter((item) => item.match.overallStatus !== 'NOT_ELIGIBLE') : []; },
  getOffersByBuyer: async () => read().offers.filter((offer) => offer.buyerId === 'BUYER-001'), getOffersByFarmer: async () => read().offers.filter((offer) => offer.farmerId === 'FARMER-001'),
  createOffer: async (offer: Offer) => { const db = read(); db.offers.unshift(offer); write(db); return offer; },
  acceptOffer: async (id: string) => { const db = read(); const offer = db.offers.find((item) => item.id === id); if (!offer) throw new Error('Offer not found'); offer.status = 'ACCEPTED'; const transaction: MarketplaceTransaction = { id: `TXN-${Date.now()}`, offerId: offer.id, lotId: offer.lotId, requirementId: offer.requirementId, farmerId: offer.farmerId, buyerId: offer.buyerId, quantity: offer.quantity, agreedPricePerQuintal: offer.pricePerQuintal, totalValue: offer.estimatedTotalValue, paymentTimelineDays: offer.paymentTimelineDays, transactionStatus: 'CREATED', logisticsStatus: 'NOT_PLANNED', paymentStatus: 'PENDING', createdAt: new Date().toISOString() }; db.transactions.unshift(transaction); write(db); return transaction; },
  rejectOffer: async (id: string) => { const db = read(); const offer = db.offers.find((item) => item.id === id); if (!offer) throw new Error('Offer not found'); offer.status = 'REJECTED'; write(db); return offer; },
  getTransactionsByBuyer: async () => read().transactions.filter((item) => item.buyerId === 'BUYER-001'), getTransactionsByFarmer: async () => read().transactions.filter((item) => item.farmerId === 'FARMER-001'),
};
